version: '3.8'

services:
  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=toor
      - DB_DATABASE=test-shopper
 
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=test-shopper
      - MYSQL_USER=shopperuser
      - MYSQL_PASSWORD=toor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: {}
